### ISSUE TITLE
NPM Package?

### ISSUE THREAD

**Issue by mischkl** [ui-router/dsr#1]
Hi,
We'd love to use this but I couldn't find an NPM package. Any chance you could publish one?
Thanks for all the great work, @christopherthielen !
Cheers

**Comment by christopherthielen** [comment]
I apologize for the lack of activity.  I'll get this published and moved to its final home at `@uirouter/dsr` as soon as possible.  It's at the bottom of a long list of packages that need publishing including ui-router-core, angular-ui-router 1.0 final and ui-router-ng2.  They're all moving to `@uirouter/*` btw

**Comment by jfoo1984** [comment]
any update on this?  would like to use this with ng1 as well, but also need to work through the issues discussed here: https://github.com/ui-router/sticky-states/issues/4

**Comment by christopherthielen** [comment]
the other packages are now fully published under the `@uirouter/*` npm org.  dsr and sticky states are next

**Comment by christopherthielen** [comment]
DSR has been published along with sticky states

**Comment by mischkl** [comment]
Awesome!
