### ISSUE TITLE
Feature Request: Release 1.0.3 to npm registry

### ISSUE THREAD

**Issue by sambernet** [ui-router/dsr#9]
We use `ui-router/dsr` in our angularJs frontends and are impacted by Issue #2 

I just noticed that the issue has already been closed and is in the 1.0.3 milestone - which does not contain further issues.

Would you mind doing a release of that to `npmjs.com` registry? This would simplify working around that problem heavily for us. I'd like to avoid to npm install `ui-router/dsr` directly from github or creating a fork just to publish with a different name.

**Comment by christopherthielen** [comment]
https://github.com/ui-router/dsr/releases/tag/1.0.3

Sorry for the delay!
